import DashboardLayout from "./dashboardLayout";

export const metadata = {
    title: "Dashboard | Mauri Films",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <DashboardLayout>
            {children}
        </DashboardLayout>
    );
}
